behaviors:
  ActionGame:
    trainer_type: ppo

    max_steps: 2000000
    time_horizon: 128
    summary_freq: 10000
    keep_checkpoints: 5

    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      learning_rate_schedule: linear

      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0


environment_parameters:
  blockWidthMin:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.5
      max_value: 2.0

  blockWidthMax:
    sampler_type: uniform
    sampler_parameters:
      min_value: 2.0
      max_value: 4.0

  blockInterval:
    sampler_type: uniform
    sampler_parameters:
      min_value: 30
      max_value: 70

  blockSpeed:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.08
      max_value: 0.32
