behaviors:
  RollerBall:
    trainer_type: ppo

    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5

    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 0.0003
      learning_rate_schedule: linear

      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

environment_parameters:
  mass:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.5
      max_value: 10

  scale:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.75
      max_value: 3
